<?php

namespace Blogger\BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function getLatestPosts($limit = null)
    {
        $qb = $this->createQueryBuilder('p')
                    ->select('p')
                    // ->leftJoin('p.comments', 'c')
                    ->addOrderBy('p.created', 'DESC');

        if ((int)$limit) {
            $qb->setMaxResults((int)$limit);
        }

        return $qb->getQuery()->getResult();

    }
}
